spring:
  application:
  name: safe-escape-backend

  datasource:
    url: jdbc:mysql://localhost:3306/escape?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none   # create, update, validate, none ? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  server:
    port: 8080

  data:
    redis:
      host: 127.0.0.1
      port: 6379

